//! Proc macros for kappa-registry.
//!
//! `#[derive(ClassifyEndpoint)]` generates an `op_class()` method on an
//! enum whose variants are annotated with `#[op_class(Read)]`,
//! `#[op_class(Write)]`, `#[op_class(Admin)]`, or `#[op_class(Exempt)]`.
//!
//! Missing annotations are a compile error -- every variant must declare
//! its operation class. This prevents silent misclassification when new
//! endpoints are added.

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Data, DeriveInput, Fields, Ident, Meta};

/// Derive `op_class(&self) -> OpClass` from per-variant `#[op_class(...)]`
/// attributes. Every variant must have exactly one annotation or compilation
/// fails. See `routes/mod.rs` for usage.
#[proc_macro_derive(ClassifyEndpoint, attributes(op_class))]
pub fn derive_classify_endpoint(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;
    let generics = &input.generics;
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();

    let variants = match &input.data {
        Data::Enum(data) => &data.variants,
        _ => {
            return syn::Error::new_spanned(
                &input,
                "ClassifyEndpoint can only be derived on enums",
            )
            .to_compile_error()
            .into();
        }
    };

    let mut arms = Vec::new();

    for variant in variants {
        let vname = &variant.ident;

        // Find #[op_class(ClassName)] attribute
        let class_ident = variant.attrs.iter().find_map(|attr| {
            if !attr.path().is_ident("op_class") {
                return None;
            }
            match &attr.meta {
                Meta::List(list) => {
                    let tokens = list.tokens.clone();
                    syn::parse2::<Ident>(tokens).ok()
                }
                _ => None,
            }
        });

        let class_ident = match class_ident {
            Some(id) => id,
            None => {
                return syn::Error::new_spanned(
                    variant,
                    format!(
                        "variant `{}` is missing #[op_class(Exempt|Read|Write|Admin)]",
                        vname
                    ),
                )
                .to_compile_error()
                .into();
            }
        };

        // Generate the match arm with appropriate field pattern
        let pattern = match &variant.fields {
            Fields::Unit => quote! { Self::#vname },
            Fields::Named(_) => quote! { Self::#vname { .. } },
            Fields::Unnamed(_) => quote! { Self::#vname(..) },
        };

        arms.push(quote! {
            #pattern => crate::ratelimit::OpClass::#class_ident,
        });
    }

    let expanded = quote! {
        impl #impl_generics #name #ty_generics #where_clause {
            /// Returns the operation class for rate limiting.
            /// Generated by `#[derive(ClassifyEndpoint)]`.
            pub fn op_class(&self) -> crate::ratelimit::OpClass {
                match self {
                    #(#arms)*
                }
            }
        }
    };

    expanded.into()
}
